spring:
  application:
    name: ai-document-extraction-api

  profiles:
    active: mock

  #datasource:
  #  url: jdbc:postgresql://localhost:5432/ai_document_extraction
  #  username: ${DB_USERNAME:postgres}
  #  password: ${DB_PASSWORD:postgres}
  #  driver-class-name: org.postgresql.Driver

  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  open-in-view: false
  #  properties:
  #    hibernate:
  #      format_sql: true
  #  show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.example.aidocument: DEBUG